window.KidzAuth={
 busy:false,
 async boot(){try{await kidzCloud.init();const session=await kidzCloud.session();this.render(session);if(session)await this.enterParent(session)}catch(e){this.render(null,e.message)}},
 render(session,error=""){const root=document.getElementById("cloudAuth");if(!root)return;
  if(session){root.innerHTML='<div class="cloud-user auth-success"><div><span class="auth-check">✓</span><div><b>'+this.escape(session.user.email)+'</b><span>Ouderaccount actief</span></div></div><button class="ghost" id="cloudLogout">Uitloggen</button></div><div id="authStatus" class="auth-status">Parent Mode wordt geladen…</div>';document.getElementById("cloudLogout").onclick=async()=>{await kidzCloud.signOut();location.reload()};return}
  root.innerHTML='<div class="cloud-auth-box"><div class="auth-tabs"><button class="auth-tab active" data-auth-tab="login">Inloggen</button><button class="auth-tab" data-auth-tab="signup">Account maken</button></div><div id="authStatus" class="auth-status '+(error?"error":"")+'">'+this.escape(error||"Log in om Parent Mode te openen.")+'</div><div class="cloud-auth-grid"><label class="field"><span>E-mail</span><input id="cloudEmail" type="email" autocomplete="email" placeholder="ouder@example.nl"></label><label class="field"><span>Wachtwoord</span><input id="cloudPassword" type="password" autocomplete="current-password" minlength="8" placeholder="Minimaal 8 tekens"></label><label class="field signup-only hidden"><span>Jouw naam</span><input id="cloudName" autocomplete="name" placeholder="Bijvoorbeeld Levi"></label><button class="primary full" id="cloudSubmit">Inloggen</button><button class="auth-link" id="forgotPassword">Wachtwoord vergeten?</button></div></div>';
  let tab="login";const setTab=t=>{tab=t;root.querySelectorAll(".auth-tab").forEach(x=>x.classList.toggle("active",x.dataset.authTab===t));root.querySelectorAll(".signup-only").forEach(x=>x.classList.toggle("hidden",t!=="signup"));cloudSubmit.textContent=t==="login"?"Inloggen":"Ouderaccount maken";cloudPassword.autocomplete=t==="login"?"current-password":"new-password";this.status(t==="login"?"Vul je accountgegevens in.":"Maak een ouderaccount aan.")};root.querySelectorAll("[data-auth-tab]").forEach(x=>x.onclick=()=>setTab(x.dataset.authTab));cloudSubmit.onclick=()=>tab==="login"?this.login():this.signup();forgotPassword.onclick=()=>this.reset();[cloudEmail,cloudPassword].forEach(x=>x.addEventListener("keydown",e=>{if(e.key==="Enter")cloudSubmit.click()}))
 },
 status(message,type=""){const x=document.getElementById("authStatus");if(x){x.textContent=message;x.className="auth-status "+type}},
 setBusy(on,label="Even wachten…"){this.busy=on;const b=document.getElementById("cloudSubmit");if(b){b.disabled=on;if(on){b.dataset.old=b.textContent;b.textContent=label}else if(b.dataset.old)b.textContent=b.dataset.old}},
 async login(){if(this.busy)return;const email=cloudEmail.value.trim(),password=cloudPassword.value;if(!email||!password)return this.status("Vul je e-mail en wachtwoord in.","error");this.setBusy(true,"Inloggen…");try{const data=await kidzCloud.signIn(email,password);const session=data?.session||await kidzCloud.session();if(!session)throw new Error("Geen actieve sessie ontvangen.");this.status("Ingelogd. Parent Mode wordt voorbereid…","success");await this.enterParent(session)}catch(e){this.status(this.friendly(e),"error");this.setBusy(false)}},
 async signup(){if(this.busy)return;const email=cloudEmail.value.trim(),password=cloudPassword.value,name=cloudName.value.trim();if(!email||!email.includes("@"))return this.status("Vul een geldig e-mailadres in.","error");if(password.length<8)return this.status("Gebruik minimaal 8 tekens voor je wachtwoord.","error");if(!name)return this.status("Vul je naam in.","error");this.setBusy(true,"Account maken…");try{const data=await kidzCloud.signUp(email,password,name,"parent");if(data?.session){this.status("Account gemaakt. Parent Mode wordt geopend…","success");await this.enterParent(data.session);return}this.status("Account gemaakt! Bevestig eerst de e-mail van Supabase en log daarna in.","success");this.setBusy(false)}catch(e){this.status(this.friendly(e),"error");this.setBusy(false)}},
 async enterParent(session){try{this.status("Gezin en instellingen laden…");await KidzOnboarding.ensure();if(window.KidzCloudFilters)await Promise.allSettled([KidzCloudFilters.syncToLocal(),KidzCloudUsage.hydrate(),KidzCloudActivity.hydrate()]);if(typeof applyCloudToLocal==="function")applyCloudToLocal();if(typeof openMode==="function"){openMode("parent");toast("Welkom in Parent Mode")}else throw new Error("Parent Mode kon niet worden gestart.")}catch(e){console.error("Parent bootstrap",e);this.status("Account is ingelogd, maar Parent Mode kon niet laden: "+this.friendly(e),"error");this.setBusy(false)}},
 async reset(){const email=cloudEmail.value.trim();if(!email||!email.includes("@"))return this.status("Vul eerst je e-mailadres in.","error");try{await kidzCloud.client.auth.resetPasswordForEmail(email,{redirectTo:location.href});this.status("Resetlink verstuurd. Controleer je e-mail.","success")}catch(e){this.status(this.friendly(e),"error")}},
 friendly(e){const m=String(e?.message||e||"Onbekende fout");if(/invalid login/i.test(m))return"Deze e-mail/wachtwoordcombinatie klopt niet.";if(/email not confirmed/i.test(m))return"Bevestig eerst je e-mailadres via de mail van Supabase.";if(/already registered|already been registered/i.test(m))return"Er bestaat al een account met dit e-mailadres. Kies Inloggen.";if(/password/i.test(m)&&/least|characters/i.test(m))return"Je wachtwoord is te kort.";return m},
 escape(v){return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
};