window.KidzAuth={
 busy:false,
 async boot(){try{await kidzCloud.init();const session=await kidzCloud.session();this.render(session);if(session)await this.enterParent(session)}catch(e){this.render(null,e.message)}},
 render(session,error=""){const root=document.getElementById("cloudAuth");if(!root)return;
  if(session){root.innerHTML='<div class="cloud-user auth-success"><div><span class="auth-check">✓</span><div><b>'+this.escape(session.user.email)+'</b><span>Ouderaccount actief</span></div></div><button class="ghost" id="cloudLogout">Uitloggen</button></div><div id="authStatus" class="auth-status">Parent Mode wordt geladen…</div>';document.getElementById("cloudLogout").onclick=async()=>{await kidzCloud.signOut();location.reload()};return}
  root.innerHTML='<div class="cloud-auth-box"><div class="auth-tabs"><button class="auth-tab active" data-auth-tab="login">Inloggen</button><button class="auth-tab" data-auth-tab="signup">Account maken</button></div><div id="authStatus" class="auth-status '+(error?"error":"")+'">'+this.escape(error||"Log in om Parent Mode te openen.")+'</div><div class="cloud-auth-grid"><label class="field"><span>E-mail</span><input id="cloudEmail" type="email" autocomplete="email" placeholder="ouder@example.nl"></label><label class="field"><span>Wachtwoord</span><input id="cloudPassword" type="password" autocomplete="current-password" minlength="8" placeholder="Minimaal 8 tekens"></label><label class="field signup-only hidden"><span>Jouw naam</span><input id="cloudName" autocomplete="name" placeholder="Bijvoorbeeld Levi"></label><button class="primary full" id="cloudSubmit">Inloggen</button><button class="auth-link" id="forgotPassword">Wachtwoord vergeten?</button></div></div>';
  let tab="login";const setTab=t=>{tab=t;root.querySelectorAll(".auth-tab").forEach(x=>x.classList.toggle("active",x.dataset.authTab===t));root.querySelectorAll(".signup-only").forEach(x=>x.classList.toggle("hidden",t!=="signup"));cloudSubmit.textContent=t==="login"?"Inloggen":"Ouderaccount maken";cloudPassword.autocomplete=t==="login"?"current-password":"new-password";this.status(t==="login"?"Vul je accountgegevens in.":"Maak een ouderaccount aan.")};root.querySelectorAll("[data-auth-tab]").forEach(x=>x.onclick=()=>setTab(x.dataset.authTab));cloudSubmit.onclick=()=>tab==="login"?this.login():this.signup();forgotPassword.onclick=()=>this.reset();[cloudEmail,cloudPassword].forEach(x=>x.addEventListener("keydown",e=>{if(e.key==="Enter")cloudSubmit.click()}))
 },
 status(message,type=""){const x=document.getElementById("authStatus");if(x){x.textContent=message;x.className="auth-status "+type}},
 setBusy(on,label="Even wachten…"){this.busy=on;const b=document.getElementById("cloudSubmit");if(b){b.disabled=on;if(on){b.dataset.old=b.textContent;b.textContent=label}else if(b.dataset.old)b.textContent=b.dataset.old}},
 async login(){if(this.busy)return;const email=cloudEmail.value.trim(),password=cloudPassword.value;if(!email||!password)return this.status("Vul je e-mail en wachtwoord in.","error");this.setBusy(true,"Inloggen…");try{const data=await kidzCloud.signIn(email,password);const session=data?.session||await kidzCloud.session();if(!session)throw new Error("Geen actieve sessie ontvangen.");this.status("Ingelogd. Parent Mode wordt voorbereid…","success");await this.enterParent(session)}catch(e){this.status(this.friendly(e),"error");this.setBusy(false)}},
 async signup(){if(this.busy)return;const email=cloudEmail.value.trim(),password=cloudPassword.value,name=cloudName.value.trim();if(!email||!email.includes("@"))return this.status("Vul een geldig e-mailadres in.","error");if(password.length<8)return this.status("Gebruik minimaal 8 tekens voor je wachtwoord.","error");if(!name)return this.status("Vul je naam in.","error");this.setBusy(true,"Account maken…");try{const data=await kidzCloud.signUp(email,password,name,"parent");if(data?.session){this.status("Account gemaakt. Parent Mode wordt geopend…","success");await this.enterParent(data.session);return}this.pendingEmail=email;this.showVerification(email)}catch(e){this.status(this.friendly(e),"error");this.setBusy(false)}},
 showVerification(email){const root=document.getElementById("cloudAuth");this.busy=false;root.innerHTML='<div class="verify-card"><div class="verify-icon">✉</div><span class="eyebrow">E-MAIL BEVESTIGEN</span><h3>Check je inbox</h3><p class="muted">We hebben een 6-cijferige KidzControl-code gestuurd naar <b>'+this.escape(email)+'</b>. De code is 10 minuten geldig.</p><div class="otp-inputs" id="otpInputs">'+[0,1,2,3,4,5].map(i=>'<input inputmode="numeric" maxlength="1" aria-label="Cijfer '+(i+1)+'">').join("")+'</div><div id="authStatus" class="auth-status">Voer de code uit de e-mail in.</div><button class="primary full" id="verifyOtp">Account bevestigen</button><button class="auth-link" id="resendOtp" disabled>Nieuwe code over <span id="resendCount">60</span>s</button><button class="auth-link" id="backLogin">Terug naar inloggen</button></div>';const inputs=[...document.querySelectorAll("#otpInputs input")];inputs.forEach((x,i)=>{x.oninput=()=>{x.value=x.value.replace(/\D/g,"").slice(-1);if(x.value&&inputs[i+1])inputs[i+1].focus()};x.onkeydown=e=>{if(e.key==="Backspace"&&!x.value&&inputs[i-1])inputs[i-1].focus()};x.onpaste=e=>{const digits=e.clipboardData.getData("text").replace(/\D/g,"").slice(0,6);if(digits){e.preventDefault();digits.split("").forEach((d,j)=>{if(inputs[j])inputs[j].value=d});inputs[Math.min(digits.length,6)-1]?.focus()}}});inputs[0]?.focus();verifyOtp.onclick=()=>this.verify(email,inputs.map(x=>x.value).join(""));backLogin.onclick=()=>this.render(null);let n=60;const timer=setInterval(()=>{const el=document.getElementById("resendCount");if(!el){clearInterval(timer);return}n--;el.textContent=n;if(n<=0){clearInterval(timer);resendOtp.disabled=false;resendOtp.textContent="Nieuwe code sturen";resendOtp.onclick=()=>this.resend(email)}},1000)},
 async verify(email,token){if(!/^\d{6}$/.test(token))return this.status("Vul de volledige 6-cijferige code in.","error");this.status("Code controleren…");try{const data=await kidzCloud.verifySignupOtp(email,token);if(!data?.session)throw new Error("Bevestiging gelukt, maar er is geen sessie gestart.");this.status("E-mail bevestigd! Parent Mode wordt geopend…","success");await this.enterParent(data.session)}catch(e){this.status(/expired/i.test(String(e.message))?"Deze code is verlopen. Vraag een nieuwe code aan.":this.friendly(e),"error")}},
 async resend(email){try{document.getElementById("resendOtp").disabled=true;await kidzCloud.resendSignup(email);this.status("Nieuwe code verstuurd.","success");setTimeout(()=>this.showVerification(email),800)}catch(e){this.status(this.friendly(e),"error")}},
 async enterParent(session){try{this.status("Gezin en instellingen laden…");await KidzOnboarding.ensure();if(window.KidzCloudFilters)await Promise.allSettled([KidzCloudFilters.syncToLocal(),KidzCloudUsage.hydrate(),KidzCloudActivity.hydrate()]);if(typeof applyCloudToLocal==="function")applyCloudToLocal();if(typeof openMode==="function"){openMode("parent");toast("Welkom in Parent Mode")}else throw new Error("Parent Mode kon niet worden gestart.")}catch(e){console.error("Parent bootstrap",e);this.status("Account is ingelogd, maar Parent Mode kon niet laden: "+this.friendly(e),"error");this.setBusy(false)}},
 async reset(){const email=cloudEmail.value.trim();if(!email||!email.includes("@"))return this.status("Vul eerst je e-mailadres in.","error");try{await kidzCloud.client.auth.resetPasswordForEmail(email,{redirectTo:location.href});this.status("Resetlink verstuurd. Controleer je e-mail.","success")}catch(e){this.status(this.friendly(e),"error")}},
 friendly(e){const m=String(e?.message||e||"Onbekende fout");if(/invalid login/i.test(m))return"Deze e-mail/wachtwoordcombinatie klopt niet.";if(/email not confirmed/i.test(m))return"Bevestig eerst je e-mailadres via de mail van Supabase.";if(/already registered|already been registered/i.test(m))return"Er bestaat al een account met dit e-mailadres. Kies Inloggen.";if(/password/i.test(m)&&/least|characters/i.test(m))return"Je wachtwoord is te kort.";return m},
 escape(v){return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
};