class KidzCloudState {
 constructor(){this.family=null;this.children=[];this.child=null;this.rules=null;this.requests=[];this.listeners=new Set();this.loading=false}
 onChange(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn)}
 emit(reason="cloud"){for(const fn of this.listeners){try{fn(this,reason)}catch(e){console.error(e)}}}
 async bootstrap(){if(!kidzCloud.ready)await kidzCloud.init();const session=await kidzCloud.session();if(!session)return false;this.loading=true;try{let member=await kidzCloud.family();if(!member){const {data,error}=await kidzCloud.client.rpc("bootstrap_family",{display_name:"Mijn gezin"});if(error)throw error;member=await kidzCloud.family()}this.family=member;this.children=await kidzCloud.children(member.family_id);if(!this.children.length){const {data,error}=await kidzCloud.client.from("child_profiles").insert({family_id:member.family_id,display_name:"Milan",age_group:"10-12",avatar:"M"}).select().single();if(error)throw error;this.children=[data]}this.child=this.children[0];this.rules=await kidzCloud.rules(this.child.id);if(!this.rules){this.rules=await kidzCloud.upsertRules(this.child.id,{daily_limit:180,extra_minutes:0,paused:false,bedtime_enabled:true,bedtime_start:"21:30",bedtime_end:"07:00",school_enabled:true,school_start:"08:30",school_end:"15:00",safe_search:true,block_adult:true})}this.requests=await kidzCloud.requests(this.child.id);kidzCloud.unsubscribe();kidzCloud.subscribe(this.child.id,()=>this.refresh("realtime"));this.emit("bootstrap");return true}finally{this.loading=false}}
 async refresh(reason="refresh"){if(!this.child)return;this.rules=await kidzCloud.rules(this.child.id);this.requests=await kidzCloud.requests(this.child.id);this.emit(reason)}
 async updateRules(patch,event="RULES_UPDATED"){if(!this.child)throw new Error("Geen cloud-kindprofiel actief");this.rules=await kidzCloud.upsertRules(this.child.id,patch);await kidzCloud.addEvent(this.child.id,event,patch);this.emit(event);return this.rules}
 async request(type,title,details){if(!this.child)throw new Error("Geen cloud-kindprofiel actief");const r=await kidzCloud.createRequest(this.child.id,type,title,details);this.requests.unshift(r);this.emit("REQUEST_CREATED");return r}
 async resolve(id,status){const r=await kidzCloud.resolveRequest(id,status);const i=this.requests.findIndex(x=>x.id===id);if(i>=0)this.requests[i]=r;if(status==="approved"&&r.type==="time")await this.updateRules({extra_minutes:(this.rules?.extra_minutes||0)+30},"EXTRA_TIME_GRANTED");this.emit("REQUEST_RESOLVED");return r}
 async renameChild(name,ageGroup){const {data,error}=await kidzCloud.client.from("child_profiles").update({display_name:name,age_group:ageGroup,avatar:(name[0]||"K").toUpperCase()}).eq("id",this.child.id).select().single();if(error)throw error;this.child=data;this.emit("PROFILE_UPDATED")}
 toLocalPatch(){if(!this.child||!this.rules)return null;return{child:{name:this.child.display_name,avatar:this.child.avatar,ageGroup:this.child.age_group},screen:{dailyLimit:this.rules.daily_limit,extra:this.rules.extra_minutes,paused:this.rules.paused},bedtime:{enabled:this.rules.bedtime_enabled,start:String(this.rules.bedtime_start).slice(0,5),end:String(this.rules.bedtime_end).slice(0,5)},school:{enabled:this.rules.school_enabled,start:String(this.rules.school_start).slice(0,5),end:String(this.rules.school_end).slice(0,5)}}}
}
window.kidzCloudState=new KidzCloudState();