window.KidzPages={
 head(kicker,title,desc){return '<div class="section-title"><span class="eyebrow">'+kicker+'</span><h2>'+title+'</h2><p class="muted">'+desc+'</p></div>'},
 metric(label,value,sub){return '<article class="stat"><span>'+label+'</span><strong>'+value+'</strong><small>'+sub+'</small></article>'},
 overview(){const r=window.state||{},req=(r.requests||[]).filter(x=>x.status==="open").length;return this.head("COMMAND CENTER","Gezinsdashboard","Een uitgebreider overzicht van regels, tijd, verzoeken en beveiliging.")+'<div class="stats-grid">'+this.metric("Vandaag",window.fmt?fmt(r.screen.used):r.screen.used,"schermtijd geregistreerd")+this.metric("Resterend",window.fmt?fmt(window.remaining()):"-","beschikbaar")+this.metric("Open verzoeken",req,"wachten op antwoord")+this.metric("Security",KidzSecurity.score()+"%","configuratiescore")+'</div><div class="three-col"><article class="panel feature-card"><span class="feature-icon">◷</span><h3>Schermtijd</h3><p>Daglimieten, extra tijd en tijdelijke pauzes.</p><button class="ghost" data-nav="screen">Beheren</button></article><article class="panel feature-card"><span class="feature-icon">▣</span><h3>Weekplanning</h3><p>Schooltijd, bedtijd en routines per dag.</p><button class="ghost" data-nav="schedule">Open planning</button></article><article class="panel feature-card"><span class="feature-icon">◉</span><h3>Bescherming</h3><p>Sites, apps, categorieën en uitzonderingen.</p><button class="ghost" data-nav="filters">Filters openen</button></article></div>'},
 analytics(){const vals=state.activity||[],sum=vals.reduce((a,b)=>a+b,0),avg=Math.round(sum/Math.max(1,vals.length)),max=Math.max(...vals,0);return this.head("ANALYTICS","Gebruik & trends","Bekijk patronen zonder verborgen monitoring.")+'<div class="stats-grid">'+this.metric("7 dagen",sum+"m","totaal")+this.metric("Gemiddeld",avg+"m","per dag")+this.metric("Piekdag",max+"m","hoogste gebruik")+this.metric("Vandaag",state.screen.used+"m","geregistreerd")+'</div><article class="panel"><div class="panel-head"><div><span class="eyebrow">WEEK</span><h3>Schermtijdtrend</h3></div></div><div id="activityChart" class="bars big-bars"></div></article>'},
 categories(){return this.head("CONTENT","Categoriebeheer","Bepaal welke soorten content in KidzControl zijn toegestaan.")+'<div class="category-grid">'+KidzFeatures.categories.map(c=>'<article class="category-card"><div><b>'+c+'</b><small>Contentcategorie</small></div><button class="switch '+(state.filters.categories.includes(c)?"on":"")+'" data-action="toggleCategory" data-value="'+c+'"><i></i></button></article>').join("")+'</div>'},
 devices(){return this.head("APPARATEN","Apparaten","V1 ondersteunt één kindapparaat; hier zie je de huidige browsermogelijkheden.")+'<article class="panel">'+KidzDevice.render()+'</article><article class="panel info-panel"><b>Native apparaatbeheer komt later</b><p>Een GitHub Pages-site kan Windows of Android niet zelfstandig vergrendelen. De toekomstige KidzControl Agent gebruikt expliciete installatie en permissies.</p></article>'},
 security(){return this.head("SECURITY","Security Center","Controleer de beveiligingsstatus van deze KidzControl-installatie.")+'<div class="two-col"><article class="panel">'+KidzSecurity.render()+'</article><article class="panel"><h3>Privacyprincipes</h3><div class="rule-row"><b>RLS databasebeveiliging</b><span class="status-ok">Actief</span></div><div class="rule-row"><b>Service-role key in browser</b><span class="status-ok">Nee</span></div><div class="rule-row"><b>Verborgen keylogging</b><span class="status-ok">Nee</span></div><div class="rule-row"><b>Camera/microfoon monitoring</b><span class="status-ok">Nee</span></div></article></div>'},
 appearance(){return this.head("PERSONALISATIE","Weergave","Pas KidzControl aan zonder de interface druk te maken.")+'<div class="three-col"><button class="appearance-card" data-action="setTheme" data-value="dark"><span class="theme-preview dark-preview"></span><b>Donker</b></button><button class="appearance-card" data-action="setTheme" data-value="light"><span class="theme-preview light-preview"></span><b>Licht</b></button><button class="appearance-card" data-action="setTheme" data-value="auto"><span class="theme-preview auto-preview"></span><b>Systeem</b></button></div>'},
 family(){const child=kidzCloudState?.child;return this.head("GEZIN","Gezin & profielen","Beheer de profielen die bij KidzControl horen.")+'<div class="profile-showcase"><div class="profile-avatar">'+esc(state.child.avatar)+'</div><div><span class="eyebrow">KINDPROFIEL</span><h2>'+esc(state.child.name)+'</h2><p class="muted">Leeftijdsgroep '+esc(state.child.ageGroup)+(child?" · Cloudprofiel actief":" · Lokaal profiel")+'</p></div><button class="primary" data-nav="profile">Profiel aanpassen</button></div><article class="panel info-panel"><b>Meerdere kinderen</b><p>De database ondersteunt meerdere kindprofielen. De huidige UI focust volgens je V1-keuze op één actief kind; de profielwisselaar is voorbereid voor een volgende iteratie.</p></article>'},
 notificationCenter(){return this.head("INBOX","Notificatiecentrum","Belangrijke KidzControl-gebeurtenissen en verzoeken.")+'<div class="two-col"><article class="panel"><h3>Browsermeldingen</h3><p class="muted">Sta meldingen toe voor verzoeken en belangrijke wijzigingen.</p><button class="primary" data-action="enableNotifications">Meldingen inschakelen</button></article><article class="panel"><h3>Recente events</h3>'+eventRows()+'</article></div>'},
 kidAccess(){return this.head("AANVRAGEN","Toegang vragen","Stuur een duidelijk verzoek naar Parent Mode.")+'<div class="request-composer panel"><label class="field"><span>Website of app</span><input id="accessTarget" placeholder="Bijvoorbeeld youtube.com"></label><label class="field"><span>Waarom?</span><input id="accessReason" placeholder="Bijvoorbeeld voor huiswerk"></label><button class="primary kid-primary" data-action="requestAccessDetailed">Verzoek versturen</button></div>'}
};